name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build with VitePress
        run: |
          pnpm run docs:build
          touch .vitepress/dist/.nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # 改用 v2 更稳定
        with:
          path: .vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v2  # 与 upload-pages-artifact@v2 版本匹配
